; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    thomasfredericks/Bounce2@^2.71
    me-no-dev/ESPAsyncWebServer@^1.2.3
    me-no-dev/AsyncTCP@^1.1.1
    gin66/FastAccelStepper@^0.30.0

build_flags = 
    -std=c++17
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM

; OTA upload configuration
upload_protocol = esptool
upload_port = /dev/cu.usbmodem1101

; OTA Environment for wireless uploads
[env:freenove_esp32_s3_wroom_ota]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
lib_deps = 
    thomasfredericks/Bounce2@^2.71
    me-no-dev/ESPAsyncWebServer@^1.2.3
    me-no-dev/AsyncTCP@^1.1.1
    gin66/FastAccelStepper@^0.30.0
upload_protocol = espota
upload_port = 192.168.1.239
upload_flags = --auth=Everwood-OTA
